name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    - 'image/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '28.1'
          - 'snapshot'
    steps:
      - uses: actions/checkout@v1
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Install cask
        run: |
          git clone https://github.com/cask/cask ~/.cask
          echo "${HOME}/.cask/bin" >> $GITHUB_PATH
      - name: Run tests
        run: make test
